language: python
dist: xenial
sudo: true

python:
  - '3.6'

service:
  - docker

install:
  - sudo apt-get install jq

script:
  - ./build.sh

#deploy:
#  provider: script
#  script: bash publish.sh
#  on:
#    branch: master

notifications:
  email: false
