# add a line to force rebuild of Docker

RUN pip3 install aioconsole 

RUN apt-get update \
    && apt-get install -y \
        emacs \
        nano \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y \
       iproute \
    && rm -rf /var/lib/apt/lists/*
