RUN apt-get update \
    && apt-get -y --no-install-recommends install \
      clang-4.0 \
    && apt-get -y install cmake\
    && apt-get -y install make\
    && rm -rf /var/lib/apt/lists/* \
    && ln -s /usr/bin/clang-4.0 /usr/bin/clang \
    && ln -s /usr/bin/clang++-4.0 /usr/bin/clang++
