
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    build-essential \
    libfontconfig1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
  && pip3 install --upgrade pip  \
    numpy==1.19.2 \
    matplotlib==3.3.2 \
    scipy==1.5.2 \
    torch==1.6.0 \
    torchvision==0.7.0 \
    opencv-python \
  && rm -rf /var/lib/apt/lists/*

