RUN echo "deb http://ftp.debian.org/debian stretch-backports main" >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
      clang-5.0 \
    && rm -rf /var/lib/apt/lists/* \
    && ln -s /usr/bin/clang-5.0 /usr/bin/clang \
    && ln -s /usr/bin/clang++-5.0 /usr/bin/clang++
